### ISSUE TITLE
secret not accepted

### ISSUE THREAD

**Issue by Morriz** [titansoft-pte-ltd/imagepullsecret-patcher#26]
Hi, I don't see much output with `CONFIG_DEBUG` enabled, but the app complains about this pullsecret:

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: pullsecret-patcher
  labels:
    helm.sh/chart: pullsecret-patcher-0.1.0
    app.kubernetes.io/name: pullsecret-patcher
    app.kubernetes.io/instance: pullsecret-patcher
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJvdG9taSIsInBhc3N3b3JkIjoiYmxhZGlibGEiLCJlbWFpbCI6Im5vdEB1cy5lZCIsImF1dGgiOiJiM1J2YldrNllteGhaR2xpYkdFPSJ9fX0="
```

Why would it? It is a valid pull secret (password in it does not work for obvious reasons).
